language: minimal
branches:
  only:
    - master # build master branch only
install:
  - sudo apt-get -qq update
  - sudo apt-get -y install aria2
script:
  - ./blocklist-build.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: blocklist.gz
  skip_cleanup: true
  overwrite: true
