language: minimal
dist: focal
branches:
  only:
    - master # build master branch only
install:
  - sudo apt-get -qq update
  - sudo apt-get -y install aria2
script:
  - ./blocklist-build.sh
before_deploy:
  - git config --local user.name "Travis CI for ${TRAVIS_REPO_SLUG}"
  - git config --local user.email "no-reply@travis-ci.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: blocklist.gz
  skip_cleanup: true
  overwrite: true
