name: Build Blocklist
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: "0 0 23 * *"
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get -qq update
          sudo apt-get -y install aria2
          ./blocklist-build.sh
          echo "build_tag=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.build_tag }}"
          prerelease: false
          title: "Latest Blocklist"
          files: |
            blocklist.gz
