name: Build Blocklist
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * 4"
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and resolve tag
        run: |
          ./blocklist-build.sh
          echo "build_tag=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)" >> $GITHUB_ENV
      - name: Release on Main Push
        if: '!github.event.pull_request'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.build_tag }}"
          prerelease: false
          title: "${{ env.build_tag }}"
          files: |
            blocklist.gz
