name: Build Blocklist
'on':
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * 4"

permissions: {}

jobs:
  Build:
    permissions:
      id-token: write # trusted publishing + attestations
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build and resolve tag
        run: |
          ./blocklist-build.sh
          ./analyze.sh | tee stats.json
          # .beats 1000th of a day -> https://codegolf.stackexchange.com/a/272628
          # perl is available everywhere, right?
          beat=$(perl -M5.010 -e '$_=((@t=gmtime)[1]/60+$t[2]+1)/24 .000;/\d{3}/;say$&')
          echo "build_tag=$(date +'%Y.%m.%d').${beat}-$(git log --format=%h -1)" >> $GITHUB_ENV
      - name: Check if release is needed
        id: check
        continue-on-error: true
        run: |
          ./compare-previous.sh
      - name: Release on non-PRs if needed
        if: "github.event_name == 'workflow_dispatch' || ( !github.event.pull_request && steps.check.outcome == 'success' )"
        uses: "softprops/action-gh-release@v2"
        with:
          # repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ env.build_tag }}"
          prerelease: false
          name: "${{ env.build_tag }}"
          files: |
            blocklist.gz
            stats.json
