name: Build Blocklist
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: "0 0 * * 4"
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and resolve tag
        run: |
          ./blocklist-build.sh
          echo "build_tag=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)" >> $GITHUB_ENV
      - name: Check if release is needed
        id: check
        continue-on-error: true
        run: |
          ./compare-previous.sh
      - name: Release on non-PRs if needed
        if: !github.event.pull_request && steps.check.outcome == 'success'
        uses: "softprops/action-gh-release@v2"
        with:
          # repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ env.build_tag }}"
          prerelease: false
          name: "${{ env.build_tag }}"
          files: |
            blocklist.gz
