# Sample workflow to run the action
name: Permissions Advisor

permissions:
  actions: read

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: string
        default: "10"

jobs:
  advisor:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/advisor@31cf7361439cbdffbc73a3bb138b7e1662d46c9b # v1.0.2-beta6
      with:
        name: ${{ inputs.name }}
        count: ${{ fromJSON(inputs.count) }}
